version: '3.7'
services:

  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    hostname: localstack
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - EDGE_PORT=4566
      - SERVICES=sqs
      - DEBUG=true
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    ports:
      - "4566:4566"
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - ./localstack_setup:/docker-entrypoint-initaws.d/
      - /var/run/docker.sock:/var/run/docker.sock